DATA:
    ROOT: '/cluster/project/infk/cvg/students/buobm/datasets/Epic-Kitchen/videos/'
    TRAIN_FILE: 'epic_kitchen_100/top_200_classes/top_200_filtered_train.txt'
    VAL_FILE: 'epic_kitchen_100/top_200_classes/top_200_filtered_val.txt'
    DATASET: epic_kitchen_100_top_200
    NUM_FRAMES: 8
    NUM_CLASSES: 200
    LABEL_LIST: 'epic_kitchen_100/top_200_classes/top_200_class_mapping.csv'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    EPOCHS: 40
    WARMUP_EPOCHS: 3
    WEIGHT_DECAY: 0.001
    LR: 8.e-6
    BATCH_SIZE: 8
    ACCUMULATION_STEPS: 4
    LR_SCHEDULER: 'cosine'
    OPTIMIZER: 'adamw'
    OPT_LEVEL: 'O1'