DATA:
    ROOT: '/home/mischa/ETH/semester_project/Datasets/kinetics-400/k400/videos/'
    TRAIN_FILE: '/home/mischa/ETH/semester_project/Datasets/kinetics-400/k400/annotations/train.txt'
    VAL_FILE: '/home/mischa/ETH/semester_project/Datasets/kinetics-400/k400/annotations/test.txt'
    DATASET: kinetics400
    NUM_FRAMES: 8
    NUM_CLASSES: 400
    MULTI_CLASS: True
    LABEL_LIST: 'labels/kinetics_400_labels.csv'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 8
    ACCUMULATION_STEPS: 4