DATA:
    ROOT: '/cluster/project/infk/cvg/students/buobm/datasets/kinetics-400/k400/videos/'
    TRAIN_FILE: '/cluster/project/infk/cvg/students/buobm/datasets/kinetics-400/k400/annotations/train.txt'
    VAL_FILE: '/cluster/project/infk/cvg/students/buobm/datasets/kinetics-400/k400/annotations/test.txt'
    DATASET: kinetics400
    NUM_FRAMES: 8
    NUM_CLASSES: 400
    LABEL_LIST: 'labels/kinetics_400_labels.csv'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 8
    ACCUMULATION_STEPS: 4