DATA:
    ROOT: '/cluster/project/infk/cvg/students/buobm/datasets/HoloAssist/videos'
    TRAIN_FILE: 'HoloAssist/10_samples/8_2_split/train_data.txt'
    VAL_FILE: 'HoloAssist/10_samples/8_2_split/val_data.txt'
    DATASET: HoloAssist_min_10_samples_8_train
    NUM_FRAMES: 8
    NUM_CLASSES: 93
    LABEL_LIST: 'HoloAssist/10_samples/holoassist_labels.csv'
MODEL:
    ARCH: ViT-L/14
    FIX_TEXT: True
TRAIN:
    EPOCHS: 100
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.001
    LR: 8.e-6
    BATCH_SIZE: 4
    ACCUMULATION_STEPS: 8
    LR_SCHEDULER: 'step'
    OPTIMIZER: 'adam'
    OPT_LEVEL: 'O1'
    STEP_SIZE: 4
    LR_DECAY: 0.85