DATA:
    ROOT: '/cluster/project/infk/cvg/students/buobm/datasets/HoloAssist/videos'
    TRAIN_FILE: 'HoloAssist/10_samples/zero_shot/zero_shot_holoassist_dataset.txt'
    VAL_FILE: 'HoloAssist/10_samples/zero_shot/zero_shot_holoassist_dataset.txt'
    DATASET: HoloAssist_min_10_samples_8_train Acc@1_16.304_Acc@5_45.652
    NUM_FRAMES: 8
    NUM_CLASSES: 111
    LABEL_LIST: 'HoloAssist/10_samples/zero_shot/zero_shot_holoassist_labels.csv'
MODEL:
    ARCH: ViT-L/14
    FIX_TEXT: True
TRAIN:
    EPOCHS: 100
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.001
    LR: 8.e-6
    BATCH_SIZE: 4
    ACCUMULATION_STEPS: 8
    LR_SCHEDULER: 'cosine'
    OPTIMIZER: 'adamw'
    OPT_LEVEL: 'O1'
    STEP_SIZE: 10
    LR_DECAY: 0.1