DATA:
    ROOT: '/cluster/project/infk/cvg/students/buobm/datasets/HoloAssist/videos'
    TRAIN_FILE: 'HoloAssist/10_samples/train_data.txt'
    VAL_FILE: 'HoloAssist/10_samples/val_data.txt'
    DATASET: HoloAssist_min_10_samples
    NUM_FRAMES: 16
    NUM_CLASSES: 93
    LABEL_LIST: 'HoloAssist/10_samples/holoassist_labels.csv'
MODEL:
    ARCH: ViT-B/16
    FIX_TEXT: False
TRAIN:
    EPOCHS: 50
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.001
    LR: 2.e-6
    BATCH_SIZE: 4
    ACCUMULATION_STEPS: 8
    LR_SCHEDULER: 'step'
    OPTIMIZER: 'adam'
    OPT_LEVEL: 'O1'
    STEP_SIZE: 5
    LR_DECAY: 0.6
    PATIENCE: 5