DATA:
    ROOT: '/cluster/project/infk/cvg/students/buobm/datasets/HoloAssist/videos'
    TRAIN_FILE: 'HoloAssist/10_samples/zero_shot/zero_shot_holoassist_dataset.txt'
    VAL_FILE: 'HoloAssist/10_samples/zero_shot/zero_shot_holoassist_dataset.txt'
    DATASET: HoloAssist_Zero_Shot_Dataset
    NUM_FRAMES: 8
    NUM_CLASSES: 111
    LABEL_LIST: 'HoloAssist/10_samples/zero_shot/zero_shot_holoassist_labels.csv'
MODEL:
    PRETRAINED: checkpoints/vit_base_patch16_224_miil_21k.pth
    ARCH: ViT-B/32