DATA:
    ROOT: '/cluster/project/infk/cvg/students/buobm/datasets/HoloAssist/videos'
    TRAIN_FILE: 'HoloAssist/All_data/coarse_grained/4_2_split/test_and_train_data.txt'
    VAL_FILE: 'HoloAssist/All_data/coarse_grained/4_2_split/val_data.txt'
    DATASET: HoloAssist_all_data_coarse_4_2_split
    NUM_FRAMES: 8
    NUM_CLASSES: 226
    LABEL_LIST: 'HoloAssist/All_data/coarse_grained/4_2_split/holoassist_labels.csv'
MODEL:
    ARCH: ViT-B/32
    FIX_TEXT: True
TRAIN:
    EPOCHS: 100
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.001
    LR: 8.e-6
    BATCH_SIZE: 32
    ACCUMULATION_STEPS: 4
    LR_SCHEDULER: 'cosine'
    OPTIMIZER: 'adamw'
    OPT_LEVEL: 'O1'
    STEP_SIZE: 10
    LR_DECAY: 0.1